# Generated by Django 6.0.7 on 2026-08-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seed_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='terms_html',
            field=models.TextField(blank=True),
        ),
    ]
