# Generated by hand: grant approval + create permissions to existing roles.

from django.db import migrations


def add_approval_permissions(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.filter(code='manager'):
        perms = set(role.permissions or [])
        perms.add('quotation.approve')
        role.permissions = sorted(perms)
        role.save(update_fields=['permissions'])
    for role in Role.objects.filter(code='staff'):
        perms = set(role.permissions or [])
        perms.add('quotation.create')
        perms.add('quotation.edit')
        role.permissions = sorted(perms)
        role.save(update_fields=['permissions'])


def remove_approval_permissions(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    extra = ['quotation.approve', 'quotation.create', 'quotation.edit']
    for role in Role.objects.all():
        perms = set(role.permissions or [])
        changed = False
        for key in extra:
            if key in perms:
                perms.discard(key)
                changed = True
        if changed:
            role.permissions = sorted(perms)
            role.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_logo'),
    ]

    operations = [
        migrations.RunPython(add_approval_permissions, reverse_code=remove_approval_permissions),
    ]
