# Generated by hand: grant approval to admin (system) and custom roles.

from django.db import migrations


def grant_approval(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.all():
        if role.code == 'admin' or 'quotation.send' in (role.permissions or []):
            perms = set(role.permissions or [])
            perms.add('quotation.approve')
            role.permissions = sorted(perms)
            role.save(update_fields=['permissions'])


def revoke_approval(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.all():
        perms = set(role.permissions or [])
        if 'quotation.approve' in perms:
            perms.discard('quotation.approve')
            role.permissions = sorted(perms)
            role.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_quotation_approval_role_permissions'),
    ]

    operations = [
        migrations.RunPython(grant_approval, reverse_code=revoke_approval),
    ]
