# Generated by Django 6.0.7 on 2026-08-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_quotation_approval_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.CharField(blank=True, default='INR (₹)', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='default_bank',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='gstin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
