# Generated by hand: restrict the built-in staff role to raw data + tele-call.

from django.db import migrations

# Permission keys removed from the staff role template. Existing staff roles
# keep any extra permissions an admin may have assigned; these are withdrawn.
REMOVED = [
    'leads.view_raw_all',
    'quotation.view', 'quotation.create', 'quotation.edit',
    'client.view',
    'branch.view', 'category.view', 'source.view', 'company.view',
    'reports.view',
]


def strip_staff_permissions(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.filter(code='staff'):
        perms = set(role.permissions or [])
        changed = False
        for key in REMOVED:
            if key in perms:
                perms.discard(key)
                changed = True
        if changed:
            role.permissions = sorted(perms)
            role.save(update_fields=['permissions'])


def restore_staff_permissions(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.filter(code='staff'):
        perms = set(role.permissions or [])
        changed = False
        for key in REMOVED:
            if key not in perms:
                perms.add(key)
                changed = True
        if changed:
            role.permissions = sorted(perms)
            role.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_company_terms_split_and_defaults'),
    ]

    operations = [
        migrations.RunPython(strip_staff_permissions, reverse_code=restore_staff_permissions),
    ]