# Generated by hand: grant the lock-override permission to admin/system roles.

from django.db import migrations


def grant_admin_lock_override(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.filter(is_system=True):
        if 'leads.manage_lock' not in role.permissions:
            role.permissions = [*role.permissions, 'leads.manage_lock']
            role.save(update_fields=['permissions'])


def revoke_admin_lock_override(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.filter(is_system=True):
        if 'leads.manage_lock' in role.permissions:
            role.permissions = [p for p in role.permissions if p != 'leads.manage_lock']
            role.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_staff_restrict_permissions'),
    ]

    operations = [
        migrations.RunPython(grant_admin_lock_override, reverse_code=revoke_admin_lock_override),
    ]