# Generated by hand: grant the send-without-approval permission to admin/system roles.

from django.db import migrations

PERMISSION = 'quotation.send_without_approval'


def grant_admin_send_without_approval(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.filter(is_system=True):
        if PERMISSION not in role.permissions:
            role.permissions = [*role.permissions, PERMISSION]
            role.save(update_fields=['permissions'])


def revoke_admin_send_without_approval(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.filter(is_system=True):
        if PERMISSION in role.permissions:
            role.permissions = [p for p in role.permissions if p != PERMISSION]
            role.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_admin_manage_lock_permission'),
    ]

    operations = [
        migrations.RunPython(grant_admin_send_without_approval, reverse_code=revoke_admin_send_without_approval),
    ]
