# Generated by Django 5.2.17 on 2026-09-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_role_system_roles_full_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='base_currency',
            field=models.CharField(blank=True, default='INR', max_length=30),
        ),
    ]
