# Generated by hand: withdraw the "Delete own leads" permission from the
# built-in staff role. Admins can still grant it per role afterwards.

from django.db import migrations


def strip_staff_delete(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.filter(code='staff'):
        if 'leads.delete' in (role.permissions or []):
            role.permissions = [p for p in role.permissions if p != 'leads.delete']
            role.save(update_fields=['permissions'])


def restore_staff_delete(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.filter(code='staff'):
        if 'leads.delete' not in (role.permissions or []):
            role.permissions = [*role.permissions, 'leads.delete']
            role.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_email_change_request'),
    ]

    operations = [
        migrations.RunPython(strip_staff_delete, reverse_code=restore_staff_delete),
    ]