# Generated by Django 5.2.17 on 2026-10-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_backfill_manager_view_raw_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='seal',
            field=models.ImageField(blank=True, null=True, upload_to='company_seals/'),
        ),
    ]
