# Generated by Django 5.2.17 on 2026-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('time', models.CharField(blank=True, max_length=80)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('raw_leads_target', models.IntegerField(default=0)),
                ('calls_target', models.IntegerField(default=0)),
                ('quotation_target', models.IntegerField(default=0)),
                ('sales_target', models.IntegerField(default=0)),
                ('raw_leads_done', models.IntegerField(default=0)),
                ('calls_done', models.IntegerField(default=0)),
                ('quotation_done', models.IntegerField(default=0)),
                ('sales_done', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
