# Generated by Django 5.2.17 on 2026-09-10 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_company_terms_split_and_defaults'),
        ('utilities', '0002_notification_entity_id_notification_entity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafftarget',
            name='calls_done',
        ),
        migrations.RemoveField(
            model_name='stafftarget',
            name='quotation_done',
        ),
        migrations.RemoveField(
            model_name='stafftarget',
            name='raw_leads_done',
        ),
        migrations.RemoveField(
            model_name='stafftarget',
            name='sales_done',
        ),
        migrations.AddField(
            model_name='stafftarget',
            name='month',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='stafftarget',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_targets', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='stafftarget',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.AddConstraint(
            model_name='stafftarget',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'month', 'year'), name='uniq_staff_target_tenant_name_month_year'),
        ),
    ]
