# Generated by Django 5.2.17 on 2026-09-28 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='utilities_n_user_id_94597e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type', 'entity_type', 'entity_id'], name='utilities_n_user_id_9824b2_idx'),
        ),
    ]
