# Generated by Django 5.2.17 on 2026-10-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_notification_utilities_n_user_id_94597e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftarget',
            name='month',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
