from django.urls import path

from .views import (
    ClientDetailAttachmentDeleteView,
    ClientDetailAttachmentView,
    ClientDetailDetailView,
    ClientDetailListCreateView,
    ClientDetailSendToClientView,
    ClientOrderDetailView,
    ClientOrderPdfView,
    ClientQuotationDetailView,
    ClientQuotationResponseView,
    DashboardStatsView,
    LeadAssignView,
    LeadDetailView,
    LeadListView,
    LeadLockView,
    LeadMetaView,
    LeadRegisterView,
    LeadStatusView,
    LeadUnlockView,
    OrderDetailView,
    OrderListCreateView,
    OrderPdfView,
    OrderRegisterView,
    OrderSendToClientView,
    ProposalDraftView,
    ProposalTemplateDetailView,
    ProposalTemplateListView,
    PublicClientDetailAttachmentView,
    PublicClientDetailDetailView,
    QuotationApproveView,
    QuotationApproverListView,
    QuotationOtpView,
    QuotationRejectView,
    QuotationRowsView,
    QuotationSendToClientView,
    QuotationView,
)

urlpatterns = [
    path('dashboard/stats/', DashboardStatsView.as_view(), name='transactions-dashboard-stats'),
    path('leads/', LeadListView.as_view(), name='transactions-leads-list'),
    path('leads/assign/', LeadAssignView.as_view(), name='transactions-leads-assign'),
    path('leads/meta/', LeadMetaView.as_view(), name='transactions-leads-meta'),
    path('leads/register/', LeadRegisterView.as_view(), name='transactions-leads-register'),
    path('leads/my/', LeadStatusView.as_view(), name='transactions-leads-my'),
    path('leads/<pk>/lock/', LeadLockView.as_view(), name='transactions-lead-lock'),
    path('leads/<pk>/unlock/', LeadUnlockView.as_view(), name='transactions-lead-unlock'),
    path('leads/<pk>/', LeadDetailView.as_view(), name='transactions-lead-detail'),
    path('orders/', OrderListCreateView.as_view(), name='transactions-orders-list'),
    path('orders/register/', OrderRegisterView.as_view(), name='transactions-orders-register'),
    path('orders/<pk>/', OrderDetailView.as_view(), name='transactions-order-detail'),
    path('orders/<pk>/send-to-client/', OrderSendToClientView.as_view(), name='transactions-order-send-client'),
    path('orders/<pk>/pdf/', OrderPdfView.as_view(), name='transactions-order-pdf'),
    path('client-details/', ClientDetailListCreateView.as_view(), name='transactions-client-details-list'),
    path('client-details/<pk>/', ClientDetailDetailView.as_view(), name='transactions-client-detail'),
    path('client-details/<pk>/send-to-client/', ClientDetailSendToClientView.as_view(), name='transactions-client-detail-send-client'),
    path('client-details/<pk>/attachments/', ClientDetailAttachmentView.as_view(), name='transactions-client-detail-attachments'),
    path('client-details/<pk>/attachments/<aid>/', ClientDetailAttachmentDeleteView.as_view(), name='transactions-client-detail-attachment'),
    path('public/client-details/<token>/', PublicClientDetailDetailView.as_view(), name='transactions-client-detail-public'),
    path('public/client-details/<token>/attachments/', PublicClientDetailAttachmentView.as_view(), name='transactions-client-detail-public-attachments'),
    path('public/orders/<token>/', ClientOrderDetailView.as_view(), name='transactions-order-client-detail'),
    path('public/orders/<token>/pdf/', ClientOrderPdfView.as_view(), name='transactions-order-client-pdf'),
    path('quotations/approvers/', QuotationApproverListView.as_view(), name='transactions-quotation-approvers'),
    path('quotations/rows/', QuotationRowsView.as_view(), name='transactions-quotation-rows'),
    path('quotations/<lead_id>/', QuotationView.as_view(), name='transactions-quotation-detail'),
    path('quotations/<lead_id>/approval-otp/', QuotationOtpView.as_view(), name='transactions-quotation-otp'),
    path('quotations/<lead_id>/approve/', QuotationApproveView.as_view(), name='transactions-quotation-approve'),
    path('quotations/<lead_id>/reject/', QuotationRejectView.as_view(), name='transactions-quotation-reject'),
    path('quotations/<lead_id>/send-to-client/', QuotationSendToClientView.as_view(), name='transactions-quotation-send-client'),
    path('proposal-templates/', ProposalTemplateListView.as_view(), name='transactions-proposal-templates'),
    path('proposal-templates/<pk>/', ProposalTemplateDetailView.as_view(), name='transactions-proposal-template'),
    path('proposal-drafts/', ProposalDraftView.as_view(), name='transactions-proposal-drafts'),
    path('public/quotations/<token>/', ClientQuotationDetailView.as_view(), name='transactions-quotation-client-detail'),
    path('public/quotations/<token>/respond/', ClientQuotationResponseView.as_view(), name='transactions-quotation-client-respond'),
]