# Generated by Django 5.2.17 on 2026-09-08 06:19

import django.db.models.deletion
from django.db import migrations, models


STANDARD_CATEGORIES = [
    'COSMETICS STORE',
    'AUTO WASH',
    'DECOR STORES',
    'INTERIOR DESIGNERS',
    'FANCY SHOPS',
    'PERFUME SHOPE',
    'SHOPPING MALL',
    'GLASS SHOP',
    'PLYWOOD&HARDWARE',
    'ENTERTAINMENT PARK',
    'Hospital',
    'CAFES&REASTURANT',
    'REASTURANT',
    'CONVENTION CENTER',
    'THEATER',
    'EDUCATION & SCHOOL',
    'CLINIC & HEALTHCARE',
    'SALON & SPA',
]

STANDARD_SOURCES = [
    'Google Search & SEO',
    'Official Website',
    'Customer Referral',
    'Facebook Ads',
    'Instagram Campaign',
    'Existing Customer',
    'Internal Database',
    'Print & Billboard Advertisement',
    'Business Exhibition & Expo',
    'Manual Walk-in Entry',
    'LinkedIn B2B Outreach',
    'WhatsApp Business API',
    'Email Marketing Campaign',
    'Trade Show Conference',
    'Channel Partner Network',
]


def backfill_company_catalog(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    Category = apps.get_model('master', 'Category')
    Source = apps.get_model('master', 'Source')

    # Split the previously-global rows across companies: existing rows are
    # assigned to whichever company owns them via the first staff user, or the
    # first company, preserving their primary keys. Then every company receives
    # a full per-company copy of the standard catalog.
    companies = list(Company.objects.all().order_by('id'))
    if not companies:
        return

    first = companies[0]
    cat_rows = list(Category.objects.all())
    for idx, cat in enumerate(cat_rows):
        cat.company_id = companies[idx % len(companies)].id
    Category.objects.bulk_update(cat_rows, ['company'])

    src_rows = list(Source.objects.all())
    for idx, src in enumerate(src_rows):
        src.company_id = companies[idx % len(companies)].id
    Source.objects.bulk_update(src_rows, ['company'])

    for company in companies:
        existing_cats = set(Category.objects.filter(company=company).values_list('code', flat=True))
        for i, name in enumerate(STANDARD_CATEGORIES):
            code = f'CT{i:03d}'
            if code not in existing_cats:
                Category.objects.get_or_create(company=company, name=name, defaults={'code': code})
        existing_srcs = set(Source.objects.filter(company=company).values_list('code', flat=True))
        for i, name in enumerate(STANDARD_SOURCES):
            code = f'SR{i:03d}'
            if code not in existing_srcs:
                Source.objects.get_or_create(company=company, name=name, defaults={'code': code})


def unbackfill_company_catalog(apps, schema_editor):
    # No-op reverse; the historical global rows are intentionally redistributed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_company_terms_split_and_defaults'),
        ('master', '0010_branch_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='source',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_master_branchs_company_name'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_master_branchs_company_code'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_master_categorys_company_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_master_categorys_company_code'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_master_sources_company_name'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_master_sources_company_code'),
        ),
        # Data backfill runs LAST: the global unique index on code must already
        # be gone so per-company copies may reuse the same code values.
        migrations.RunPython(backfill_company_catalog, unbackfill_company_catalog),
    ]
