# Generated by Django 5.2.17 on 2026-09-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_staff_delete_own_leads'),
        ('master', '0011_category_company_source_company_alter_branch_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='uniq_master_locations_company_name'), models.UniqueConstraint(fields=('company', 'code'), name='uniq_master_locations_company_code')],
            },
        ),
    ]
