# Generated by Django 5.2.17 on 2026-08-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_no', models.CharField(blank=True, max_length=30)),
                ('lead_id', models.CharField(blank=True, max_length=30)),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('accepted_date', models.CharField(blank=True, max_length=30)),
                ('collected_by', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='Details Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('lead_id', models.CharField(blank=True, max_length=30)),
                ('proposal_no', models.CharField(blank=True, max_length=30)),
                ('proposal_date', models.CharField(blank=True, max_length=30)),
                ('customer', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('bdm', models.CharField(blank=True, max_length=120)),
                ('proposal_by', models.CharField(blank=True, max_length=120)),
                ('staff', models.CharField(blank=True, max_length=120)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('total', models.CharField(blank=True, max_length=40)),
                ('discount', models.CharField(blank=True, max_length=40)),
                ('net_amount', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='INR (₹)', max_length=30)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('default_total', models.CharField(blank=True, max_length=30)),
                ('default_discount', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(default='INR (₹)', max_length=30)),
                ('scope_html', models.TextField(blank=True)),
                ('detail_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('lead_id', models.CharField(blank=True, max_length=30)),
                ('customer', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('bdm', models.CharField(blank=True, max_length=120)),
                ('qtn_by', models.CharField(blank=True, max_length=120)),
                ('staff', models.CharField(blank=True, max_length=120)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='Not Sent', max_length=50)),
                ('total', models.CharField(blank=True, max_length=30)),
                ('discount', models.CharField(blank=True, max_length=30)),
                ('net_amount', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='INR (₹)', max_length=30)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('proposal_scope', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawLead',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('display_date', models.CharField(blank=True, max_length=50)),
                ('added_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelecallLead',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('call_status', models.CharField(default='Pending Call', max_length=40)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('last_call_date', models.CharField(blank=True, max_length=50)),
                ('next_follow_up_date', models.CharField(blank=True, max_length=30)),
                ('next_follow_up_time', models.CharField(blank=True, max_length=30)),
                ('has_follow_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=30)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='transactions.clientdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(blank=True, max_length=50)),
                ('caller', models.CharField(blank=True, max_length=120)),
                ('report', models.TextField(blank=True)),
                ('follow_up', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='transactions.telecalllead')),
            ],
            options={
                'verbose_name_plural': 'call histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
