# Generated by Django 5.2.17 on 2026-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rawlead_company_key_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlead',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
