"""Seed Raw Data up to 30 raw leads and drop phone-less telecall leads.

- Adds realistic raw (status='raw') leads so the Raw Data screen holds 30+ rows.
- Removes assigned (telecall) leads that have no phone number, since those
  cannot be reached for telecalling.
"""

from datetime import date

from django.db import migrations

EXTRA_RAW_LEADS = [
    {
        'id': 'RAW-010001',
        'company': 'THE COFFEE CORNER CAFE',
        'contact': 'Nikhil Raj',
        'phone': '9746123456',
        'email': 'nikhil@coffeecorner.in',
        'category': 'Restaurant',
        'source': 'Google Search',
        'city': 'Kochi',
        'date': date(2026, 8, 14),
        'display_date': '14 Aug 2026',
        'added_by': 'Priya Sharma',
    },
    {
        'id': 'RAW-010002',
        'company': 'BLISS SPA & WELLNESS',
        'contact': 'Meera Pillai',
        'phone': '9895123457',
        'email': 'bookings@blisswellness.com',
        'category': 'Salon & Spa',
        'source': 'Instagram Campaign',
        'city': 'Calicut',
        'date': date(2026, 8, 14),
        'display_date': '14 Aug 2026',
        'added_by': 'Alex Joseph',
    },
    {
        'id': 'RAW-010003',
        'company': 'GREEN VALLEY PUBLIC SCHOOL',
        'contact': 'Mrs. Lakshmi Menon',
        'phone': '9847234568',
        'email': 'office@greenvalleyschool.ac.in',
        'category': 'School',
        'source': 'Official Website',
        'city': 'Thrissur',
        'date': date(2026, 8, 13),
        'display_date': '13 Aug 2026',
        'added_by': 'Ananya Nair',
    },
    {
        'id': 'RAW-010004',
        'company': 'SAFETY FIRST BANK',
        'contact': 'Mr. Ramesh Iyer',
        'phone': '9446334569',
        'email': 'branches@safetyfirstbank.com',
        'category': 'Bank',
        'source': 'Manual Entry',
        'city': 'Trivandrum',
        'date': date(2026, 8, 13),
        'display_date': '13 Aug 2026',
        'added_by': 'Shanu VR',
    },
    {
        'id': 'RAW-010005',
        'company': 'CRYSTAL JEWELLERY HOUSE',
        'contact': 'Sarah Thomas',
        'phone': '9874434570',
        'email': 'care@crystaljewels.in',
        'category': 'Fancy Shops',
        'source': 'Facebook Ads',
        'city': 'Kannur',
        'date': date(2026, 8, 12),
        'display_date': '12 Aug 2026',
        'added_by': 'Priya Sharma',
    },
    {
        'id': 'RAW-010006',
        'company': 'FITNESS FACTORY GYM',
        'contact': 'Arjun Nambiar',
        'phone': '9744534571',
        'email': 'hello@fitnessfactory.in',
        'category': 'Gym & Fitness',
        'source': 'Google Search',
        'city': 'Kochi',
        'date': date(2026, 8, 12),
        'display_date': '12 Aug 2026',
        'added_by': 'Alex Joseph',
    },
    {
        'id': 'RAW-010007',
        'company': 'DREAM HOMES REALTY',
        'contact': 'Vijayakumar P',
        'phone': '9894634572',
        'email': 'sales@dreamhomesrealty.com',
        'category': 'Real Estate',
        'source': 'Customer Referral',
        'city': 'Calicut',
        'date': date(2026, 8, 11),
        'display_date': '11 Aug 2026',
        'added_by': 'Ananya Nair',
    },
    {
        'id': 'RAW-010008',
        'company': 'SHOPZY RETAIL PRIVATE LTD',
        'contact': 'Anil Kumar',
        'phone': '9844734573',
        'email': 'contact@shopzy.in',
        'category': 'E-Commerce',
        'source': 'Official Website',
        'city': 'Kochi',
        'date': date(2026, 8, 11),
        'display_date': '11 Aug 2026',
        'added_by': 'Shanu VR',
    },
    {
        'id': 'RAW-010009',
        'company': 'MARINA BAY RESORTS',
        'contact': 'Divya Krishnan',
        'phone': '9444834574',
        'email': 'reservations@marinabayresorts.com',
        'category': 'Hotel & Resorts',
        'source': 'Instagram Campaign',
        'city': 'Alleppey',
        'date': date(2026, 8, 10),
        'display_date': '10 Aug 2026',
        'added_by': 'Priya Sharma',
    },
    {
        'id': 'RAW-010010',
        'company': 'CITYVISION EYE CLINIC',
        'contact': 'Dr. Kavitha Suresh',
        'phone': '9874934575',
        'email': 'info@cityvisioneye.com',
        'category': 'Hospital',
        'source': 'Google Search',
        'city': 'Thrissur',
        'date': date(2026, 8, 10),
        'display_date': '10 Aug 2026',
        'added_by': 'Alex Joseph',
    },
    {
        'id': 'RAW-010011',
        'company': 'PREMIER MOTORS SHOWROOM',
        'contact': 'Suresh Babu',
        'phone': '9745034576',
        'email': 'premiermotors@gmail.com',
        'category': 'Automobile Dealership',
        'source': 'Facebook Ads',
        'city': 'Kochi',
        'date': date(2026, 8, 8),
        'display_date': '08 Aug 2026',
        'added_by': 'Ananya Nair',
    },
    {
        'id': 'RAW-010012',
        'company': 'TRUE MEDS PHARMACY',
        'contact': 'Faisal Rahman',
        'phone': '9895134577',
        'email': 'truemeds@outlook.com',
        'category': 'Pharmacy',
        'source': 'Manual Entry',
        'city': 'Kozhikode',
        'date': date(2026, 8, 8),
        'display_date': '08 Aug 2026',
        'added_by': 'Shanu VR',
    },
    {
        'id': 'RAW-010013',
        'company': 'WOODHAVEN FURNITURE STUDIO',
        'contact': 'Roshan K',
        'phone': '9845234578',
        'email': 'designs@woodhaven.in',
        'category': 'Furniture Store',
        'source': 'Instagram Campaign',
        'city': 'Kochi',
        'date': date(2026, 8, 7),
        'display_date': '07 Aug 2026',
        'added_by': 'Priya Sharma',
    },
    {
        'id': 'RAW-010014',
        'company': 'VOLTAGE ELECTRONICS MALL',
        'contact': 'Manu George',
        'phone': '9445334579',
        'email': 'support@voltageelectronics.com',
        'category': 'Electronics Store',
        'source': 'Google Search',
        'city': 'Trivandrum',
        'date': date(2026, 8, 7),
        'display_date': '07 Aug 2026',
        'added_by': 'Alex Joseph',
    },
    {
        'id': 'RAW-010015',
        'company': 'SUNSHINE TRAVELS & TOURS',
        'contact': 'Geetha Nair',
        'phone': '9875434580',
        'email': 'bookings@sunshinetravels.in',
        'category': 'Travel Agency',
        'source': 'Customer Referral',
        'city': 'Kochi',
        'date': date(2026, 8, 6),
        'display_date': '06 Aug 2026',
        'added_by': 'Ananya Nair',
    },
    {
        'id': 'RAW-010016',
        'company': 'GRAND PALMS HOSPITALITY',
        'contact': 'Mohamed Shafi',
        'phone': '9745534581',
        'email': 'info@grandpalms.in',
        'category': 'Hotel & Resorts',
        'source': 'Facebook Ads',
        'city': 'Kochi',
        'date': date(2026, 8, 6),
        'display_date': '06 Aug 2026',
        'added_by': 'Shanu VR',
    },
    {
        'id': 'RAW-010017',
        'company': 'NORTH PARK PRE SCHOOL',
        'contact': 'Anitha Varma',
        'phone': '9895634582',
        'email': 'hello@northparkschool.com',
        'category': 'School',
        'source': 'Official Website',
        'city': 'Kannur',
        'date': date(2026, 8, 5),
        'display_date': '05 Aug 2026',
        'added_by': 'Priya Sharma',
    },
    {
        'id': 'RAW-010018',
        'company': 'KERALA CO-OPERATIVE BANK',
        'contact': 'Mr. Joshi Kurian',
        'phone': '9845734583',
        'email': 'admin@kercoopbank.org',
        'category': 'Bank',
        'source': 'Manual Entry',
        'city': 'Thrissur',
        'date': date(2026, 8, 5),
        'display_date': '05 Aug 2026',
        'added_by': 'Alex Joseph',
    },
    {
        'id': 'RAW-010019',
        'company': 'SPICE GARDEN RESTAURANT',
        'contact': 'Jasmin A',
        'phone': '9445834584',
        'email': 'order@spicegarden.in',
        'category': 'Restaurant',
        'source': 'Google Search',
        'city': 'Kozhikode',
        'date': date(2026, 8, 4),
        'display_date': '04 Aug 2026',
        'added_by': 'Ananya Nair',
    },
    {
        'id': 'RAW-010020',
        'company': 'BLUEPRINT ARCHITECTS',
        'contact': 'Naveen Prasad',
        'phone': '9875934585',
        'email': 'studio@blueprintarch.in',
        'category': 'Interior Designers',
        'source': 'Instagram Campaign',
        'city': 'Kochi',
        'date': date(2026, 8, 4),
        'display_date': '04 Aug 2026',
        'added_by': 'Shanu VR',
    },
    {
        'id': 'RAW-010021',
        'company': 'STYLE HUB UNISEX SALON',
        'contact': 'Rita D Souza',
        'phone': '9746034586',
        'email': 'stylehub@gmail.com',
        'category': 'Salon & Spa',
        'source': 'Facebook Ads',
        'city': 'Calicut',
        'date': date(2026, 8, 3),
        'display_date': '03 Aug 2026',
        'added_by': 'Priya Sharma',
    },
    {
        'id': 'RAW-010022',
        'company': 'AQUA CLEAN LAUNDRY SERVICES',
        'contact': 'Santhosh V',
        'phone': '9896134587',
        'email': 'aquaclean@yahoo.com',
        'category': 'Others',
        'source': 'Manual Entry',
        'city': 'Trivandrum',
        'date': date(2026, 8, 3),
        'display_date': '03 Aug 2026',
        'added_by': 'Alex Joseph',
    },
    {
        'id': 'RAW-010023',
        'company': 'LA MER BOUTIQUE',
        'contact': 'Anju Mathew',
        'phone': '9846234588',
        'email': 'lamer.sales@gmail.com',
        'category': 'Fancy Shops',
        'source': 'Instagram Campaign',
        'city': 'Kochi',
        'date': date(2026, 8, 2),
        'display_date': '02 Aug 2026',
        'added_by': 'Ananya Nair',
    },
    {
        'id': 'RAW-010024',
        'company': 'NEO TECH SOLUTIONS',
        'contact': 'Sreejith Menon',
        'phone': '9446334589',
        'email': 'info@neotech.co.in',
        'category': 'Others',
        'source': 'Customer Referral',
        'city': 'Kochi',
        'date': date(2026, 8, 2),
        'display_date': '02 Aug 2026',
        'added_by': 'Shanu VR',
    },
    {
        'id': 'RAW-010025',
        'company': 'GOLDEN EAGLE CONVENTION CENTRE',
        'contact': 'Pradeep Kumar',
        'phone': '9876434590',
        'email': 'events@goldeneagle.in',
        'category': 'Convention Center',
        'source': 'Facebook Ads',
        'city': 'Kottayam',
        'date': date(2026, 8, 1),
        'display_date': '01 Aug 2026',
        'added_by': 'Priya Sharma',
    },
    {
        'id': 'RAW-010026',
        'company': 'ROOTS ORGANIC STORE',
        'contact': 'Latha Devi',
        'phone': '9746534591',
        'email': 'hello@rootsorganic.in',
        'category': 'Fancy Shops',
        'source': 'Google Search',
        'city': 'Calicut',
        'date': date(2026, 7, 31),
        'display_date': '31 Jul 2026',
        'added_by': 'Alex Joseph',
    },
    {
        'id': 'RAW-010027',
        'company': 'STAR SPORTS ARENA',
        'contact': 'Biju Thomas',
        'phone': '9896634592',
        'email': 'book@starsportsarena.com',
        'category': 'Gym & Fitness',
        'source': 'Official Website',
        'city': 'Kochi',
        'date': date(2026, 7, 30),
        'display_date': '30 Jul 2026',
        'added_by': 'Ananya Nair',
    },
]

SEED_IDS = [row['id'] for row in EXTRA_RAW_LEADS]


def seed_raw_leads(apps, schema_editor):
    Lead = apps.get_model('transactions', 'Lead')
    raw_count = Lead.objects.filter(status='raw').count()
    needed = max(0, 30 - raw_count)
    for row in EXTRA_RAW_LEADS[:needed]:
        Lead.objects.get_or_create(id=row['id'], defaults={**row, 'status': 'raw'})


def remove_phone_less_telecall(apps, schema_editor):
    Lead = apps.get_model('transactions', 'Lead')
    Lead.objects.filter(status='assigned', phone='').delete()


def unseed(apps, schema_editor):
    Lead = apps.get_model('transactions', 'Lead')
    Lead.objects.filter(id__in=SEED_IDS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_backfill_assigned_lead_tenants'),
    ]

    operations = [
        migrations.RunPython(seed_raw_leads, unseed),
        migrations.RunPython(remove_phone_less_telecall, migrations.RunPython.noop),
    ]