# Generated by Django 5.2.17 on 2026-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_seed_quotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='lead_id',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
