# Generated by Django 5.2.17 on 2026-08-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seed_staff'),
        ('transactions', '0012_alter_quotation_lead_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='uniq_lead_company_key',
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('tenant', 'company_key'), name='uniq_lead_tenant_company_key'),
        ),
    ]
