# Generated by Django 5.2.17 on 2026-08-24 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_remove_lead_uniq_lead_company_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProposalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(blank=True, max_length=60)),
                ('bdm', models.CharField(blank=True, max_length=120)),
                ('qtn_by', models.CharField(blank=True, max_length=120)),
                ('customer_person', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('scope_html', models.TextField(blank=True)),
                ('terms_html', models.TextField(blank=True)),
                ('total', models.CharField(blank=True, max_length=30)),
                ('discount', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'proposal_id'), name='uniq_proposal_draft_user_proposal')],
            },
        ),
    ]
