# Generated by Django 6.0.7 on 2026-08-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_proposaltemplate_owner_proposaldraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='revision_no',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
