# Generated by Django 5.2.17 on 2026-08-28 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_quotation_approval_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('signed_by', models.CharField(blank=True, max_length=120)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_ref', models.CharField(blank=True, max_length=120)),
                ('signature_hash', models.CharField(blank=True, max_length=160)),
                ('otp_hash', models.CharField(blank=True, max_length=160)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='transactions.quotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('quotation', 'user'), name='uniq_quotation_approval_user')],
            },
        ),
    ]
