# Generated by Django 5.2.17 on 2026-08-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_quotation_client_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContactHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('from_value', models.CharField(blank=True, max_length=255)),
                ('to_value', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.CharField(blank=True, max_length=120)),
                ('stage', models.CharField(blank=True, max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_history', to='transactions.lead')),
            ],
            options={
                'verbose_name_plural': 'lead contact histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
