# Generated by Django 5.2.17 on 2026-08-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_leadcontacthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-version_no', '-created_at']},
        ),
        migrations.AddField(
            model_name='quotation',
            name='version_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
