# Generated by Django 5.2.17 on 2026-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_alter_quotation_options_quotation_version_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='client_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='client_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_to_client_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
