# Generated by Django 5.2.17 on 2026-09-07 06:11

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_order_client_message_order_client_responded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=transactions.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
