# Generated by Django 5.2.17 on 2026-09-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_attachment_file_and_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationapproval',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
