# Generated by Django 5.2.17: lead lock fields.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_quotationapproval_otp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='locked_by',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]