# Generated by Django 5.2.17 on 2026-09-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_quotation_requested_leaves_telecall'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='client_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='client_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='client_token_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
