# Generated by Django 5.2.17 on 2026-09-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_role_system_roles_full_catalog'),
        ('transactions', '0026_clientdetail_client_token_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientdetail',
            index=models.Index(fields=['tenant', 'created_at'], name='clientdetail_tenant_created'),
        ),
        migrations.AddIndex(
            model_name='clientdetail',
            index=models.Index(fields=['status'], name='clientdetail_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdetail',
            index=models.Index(fields=['lead_id'], name='clientdetail_lead_id_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdetail',
            index=models.Index(fields=['order_no'], name='clientdetail_order_no_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'tenant', 'created_at'], name='lead_status_ten_created'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'tenant', 'assigned_to'], name='lead_status_ten_assigned'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'tenant', 'added_by'], name='lead_status_ten_addedby'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'tenant', 'date'], name='lead_status_ten_date'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'created_at'], name='lead_tenant_created'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['updated_at'], name='lead_updated_at'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='lead_source_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['category'], name='lead_category_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['call_status'], name='lead_call_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority'], name='lead_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['has_follow_up'], name='lead_has_follow_up_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'created_at'], name='order_tenant_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_status_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['lead_id'], name='order_lead_id_idx'),
        ),
    ]
