# Generated by Django 5.2.17 on 2026-09-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_lead_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
