# Generated by Django 5.2.17 on 2026-09-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sublocation',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
