# Generated by Django 5.2.17 on 2026-09-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_master_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
