# Generated by Django 5.2.17 on 2026-10-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_alter_clientdetail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
