# Generated by Django 5.2.17 on 2026-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_quotation_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldraft',
            name='customer_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
