# Generated by Django 5.2.17 on 2026-10-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_proposaldraft_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_accepted_by_designation',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_accepted_by_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
