# Generated by Django 5.2.17 on 2026-10-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0039_quotation_client_accepted_by_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
